str="Happy Learning"
print(str.upper())
print(str.split(sep='sd-'))
print(str.title())
print(str.capitalize())
print(str.casefold())
print(str.format_map(2))
print(str.format_map(2))
print(str in str)
print(str is str)
print(str not in str)